### ISSUE TITLE
App not even starting up

### ISSUE THREAD

**Issue by MathiasRenner** [jboss-dockerfiles/jbpm#17]
Using the two Docker commands in the showcase README.md (https://github.com/jboss-dockerfiles/jbpm/tree/master/showcase) on two different machines (Debian testing and Ubuntu 14.04, latest Docker CE), I cannot access the app via the browser (at `http://localhost:8080/jbpm-console`).

This is the error log (received with `docker logs`):
https://gist.github.com/anonymous/7fb37ab796cabd6b5e1ca73cd84c1c3a

I also started a discussion here: https://groups.google.com/forum/#!msg/drools-setup/pXbQZVu688A/plCtRq5vCgAJ

Anyone who can fix this?

**Comment by mbiarnes** [comment]
Hi Mathias,

I replied on this channel: https://groups.google.com/forum/#!msg/drools-setup/pXbQZVu688A/plCtRq5vCgAJ

**Comment by romartin** [comment]
Hey @MathiasRenner @mbiarnes 

I just faced with the same error using the image `jbpm-workbench-showcase:6.5.0.Final-1`. It seems that latest docker versions have some restrictions on the networking side, because using an older daemon version this does not happen. 

Anyway notice the application provides a few network endpoints, so the container (Wildfly) requires needs network privileges as well,  in order to bootstrap the different services required by the apps.  Anyway it seems an environment issue rather than something to fix in the jboss images. 

There exist different solutions for this, but the most easy one is **running the containers in `host` network mode**:
`docker run .... --network="host .."`
Please refer to [the docker run reference about networking](https://docs.docker.com/engine/reference/run/#network-settings) for more information.

@MathiasRenner Thanks for the feedback!

@mbiarnes Could you please update the documentation and add this in the troubleshooting notes? Feel free to close this ticket once having some other confirm this solution works as well. Thanks!

**Comment by mbiarnes** [comment]
edited a new Trubleshoot paragraph in docs
