### ISSUE TITLE
How do you create a custom password?

### ISSUE THREAD

**Issue by kevinreynolds** [jboss-dockerfiles/jbpm#33]
Not sure whether this is workbench or java related. 
In the showcase/etc/jbpm-users.properties I see a list of users with hashed passwords. How do I generate a custom hashed password?

**Comment by mbiarnes** [comment]
hi,
the most easy way is to start a docker image like:
docker run -p 8082:8080 -p 8002:8001 -i -t --name jbpm-workbench jboss/jbpm-workbench:latest /bin/bash
and then  
> /bin/add-user.sh  add a new user. this will add a new user and pwd .
Look at standalone/configuration/application-users.properties and standalone/configuration/application-roles.properties - copy user and the hashed pwd.
Now you can start the image with start_jbpm-wb.sh.
If you want to start jbpm-workbench-showcase you have to add the user and the hashed pwd
to the properties files. If you change the properties the changes are persistent - otherwise when removing the container these changes are lost.

**Comment by kevinreynolds** [comment]
Thanks @mbiarnes, add-user.sh did create a new user with a hashed password. However I wasn't able to login using those credentials. As a workaround, I created a user via the workbench interface, then ssh'd into the container to fetch the hash value for the user from this location `/opt/jboss/wildfly/standalone/configuration/jbpm-users.properties`

**Comment by mbiarnes** [comment]
great
